### ISSUE TITLE
Wrong AT Command in test01.py?

### ISSUE THREAD

**Issue by d0ntrash** [Seeed-Studio/ublox_lara_r2_pi_hat#2]
There might be an '=' missing in the following command.

```
# get SIM card state
if u.sendAT("AT+CSIM?\r\n", "OK\r\n"):

```
With u.debug=True I will get the following Response:
```
>AT+CSIM?
<AT+CSIM?
<ERROR
```
I checked the command in the ublox AT Command Documentation and found out, that it should be: 
```
# get SIM card state
if u.sendAT("AT+CSIM=?\r\n", "OK\r\n"):
```
Which leads to this response: 
```
>AT+CSIM=?
<AT+CSIM=?
<OK
```
Maybe this could be changed :)

**Comment by lanselambor** [comment]
@tr1core Thank you for pointing this issue out, you're right AT+CSIM? command will return ERROR always, it should rather be AT+CPIN? which used to show the SIM card state.

**Comment by d0ntrash** [comment]
Oh true. AT+CPIN makes more sense.
